//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SelectedCategory
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }

        [NotMapped]
        public IEnumerable<Category> CategoryCollection { get; set; }
    }
}
